# Generated by Django 2.1.3 on 2018-12-03 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empoyees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, upload_to='img/photo_emp/'),
        ),
    ]
