# Generated by Django 2.1.3 on 2018-12-03 12:54

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('empoyees', '0004_auto_20181203_1531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='empoyees.Employees', verbose_name='Начальник'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='photo',
            field=models.ImageField(blank=True, default='img/photo_emp/1_1_design.png', null=True, upload_to='img/photo_emp/', verbose_name='Фото'),
        ),
    ]
