# Generated by Django 2.1.3 on 2018-12-03 13:27

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('empoyees', '0005_auto_20181203_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='children', to='empoyees.Employees', verbose_name='Начальник'),
        ),
    ]
