# Generated by Django 2.1.3 on 2018-12-03 14:29

from django.db import migrations
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('empoyees', '0010_auto_20181203_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='empoyees.Employees', verbose_name='Начальник'),
        ),
    ]
